### ISSUE TITLE
Investigate sudden --features, --no-default-features, --all-features e2e test failures in CI only 

### ISSUE THREAD

**Issue by foresterre** [foresterre/cargo-msrv#1081]
- 3 e2e tests started failing suddenly on the CI
- not able to reproduce locally on both Windows 11 and Ubuntu
- consistently fails on all pipelines
- debugging on CI difficult and time consuming
- skipped these tests for now out of pragmatism, but should be investigated!

![image](https://github.com/user-attachments/assets/2d84a689-6a8e-4b13-92bb-16bd276367ad)

```
failures:

---- cargo_all_features_flag stdout ----
thread 'cargo_all_features_flag' panicked at tests/find_msrv.rs:339:68:
called `Result::unwrap()` on an `Err` value: UnableToFindAnyGoodVersion { command: "cargo check --all-features --target x86_64-unknown-linux-gnu" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- cargo_features_option stdout ----
thread 'cargo_features_option' panicked at tests/find_msrv.rs:306:68:
called `Result::unwrap()` on an `Err` value: UnableToFindAnyGoodVersion { command: "cargo check --features required_feature --target x86_64-unknown-linux-gnu" }

---- cargo_no_default_features_flag stdout ----
thread 'cargo_no_default_features_flag' panicked at tests/find_msrv.rs:372:68:
called `Result::unwrap()` on an `Err` value: UnableToFindAnyGoodVersion { command: "cargo check --no-default-features --target x86_64-unknown-linux-gnu" }


failures:
    cargo_all_features_flag
    cargo_features_option
    cargo_no_default_features_flag

test result: FAILED. 23 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 189.22s
```

**Comment by foresterre** [comment]
This may be related, although would have expected an error already before:

- https://github.com/crate-ci/clap-cargo/issues/62
- https://github.com/oli-obk/cargo_metadata/issues/254
