### ISSUE TITLE
Panic (index out of bounds) of `--min $version` >= `--max $version` [fixed in `main`]

### ISSUE THREAD

**Issue by Kijewski** [foresterre/cargo-msrv#568]
This issue was solved by #371, which was not released, yet. I think it should stay open until a fixed version gets published, in case others encounter the same problem.

---

Even though using the tool if you already know the expected msrv is a bit overkill, I don't think it should panic:

```text
$ cargo msrv  --min 1.27.0 --max 1.27.0
Fetching index
Determining the Minimum Supported Rust Version (MSRV) for toolchain x86_64-unknown-linux-gnu
Using check command cargo check
 ⠁                                ░░░░░░░░░░░░░… 00:00:00
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 9223372036854775807', …/bisector-0.3.0/src/lib.rs:136:18
```

The same if `--min` > `--max`. Especially the latter can easily happen if you accidentally flip the arguments.

**Comment by foresterre** [comment]
Thanks for the report :)!

**Comment by marcospb19** [comment]
This happened to me too, but I didn't provided a `--min` bound, just the `--max`:

```
$ cargo msrv --bisect --max 1.50.0 
Fetching index
Determining the Minimum Supported Rust Version (MSRV) for toolchain x86_64-unknown-linux-gnu
Using check command cargo check
 ⠁                                ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 00:00:00
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 9223372036854775807', /home/marcospb19/.cargo/registry/src/github.com-1ecc6299db9ec823/bisector-0.3.0/src/lib.rs:136:18
```

**Comment by marcospb19** [comment]
Oh, the repository has `edition = 2021` set, so maybe `cargo-msrv` assumed that as an `--min` value?
